import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import useSubscription from '../hooks/useSubscription'
import PremiumCard from './PremiumCard'

export default function AISummary({ article }) {
  const { user } = useAuth()
  const { loading, isPro } = useSubscription()

  const [summary, setSummary] = useState('')
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')

  async function generateSummary() {
    try {
      setGenerating(true)
      setError('')

      const res = await fetch('/api/ai-summary', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          title: article?.title,
          description: article?.description,
          userId: user?.id
        })
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate summary')
      }

      setSummary(
        data.summary
          .replace(/\*/g, '•')
          .replace(/^- /gm, '• ')
      )
    } catch (err) {
      console.error(err)
      setError('Unable to generate summary right now.')
    } finally {
      setGenerating(false)
    }
  }

  async function copySummary() {
    if (!summary) return

    try {
      await navigator.clipboard.writeText(summary)
      alert('Summary copied!')
    } catch (error) {
      console.error(error)
      alert('Unable to copy summary.')
    }
  }

  if (loading) {
    return (
      <PremiumCard glow style={{ marginTop: '35px' }}>
        <p style={{ color: '#D4AF37' }}>Checking access...</p>
      </PremiumCard>
    )
  }

  if (!isPro) {
    return (
      <PremiumCard glow style={{ marginTop: '35px' }}>
        <p style={labelStyle}>PRO FEATURE</p>
        <div style={iconStyle}>🔒</div>
        <h2 style={titleStyle}>Summary Locked</h2>

        <p style={textStyle}>
          Upgrade to VedaByte Pro to unlock intelligence summaries,
          premium reports and weekly briefs.
        </p>

        <Link to="/pricing" style={buttonStyle}>
          Upgrade to Pro
        </Link>
      </PremiumCard>
    )
  }

  return (
    <PremiumCard glow style={{ marginTop: '35px' }}>
      <div style={topRowStyle}>
        <div>
          <p style={labelStyle}>VEDABYTE INTELLIGENCE</p>
          <h2 style={titleStyle}>30 Second Summary</h2>
        </div>

        <div style={iconStyle}>🤖</div>
      </div>

      <div style={dividerStyle}></div>

      {!summary ? (
        <>
          <p style={textStyle}>
            Generate a concise intelligence summary for this article.
          </p>

          {generating && (
  <div style={loadingBoxStyle}>
    <p style={loadingTextStyle}>Reading article context...</p>
    <div style={loadingBarStyle}>
      <div style={loadingFillStyle}></div>
    </div>
    <p style={loadingSmallStyle}>Building VedaByte intelligence summary...</p>
  </div>
)}

<button
  onClick={generateSummary}
  disabled={generating}
  style={{
    ...buttonStyle,
    opacity: generating ? 0.7 : 1
  }}
>
  {generating ? 'Analyzing article...' : 'Generate Summary'}
</button>
        </>
      ) : (
        <div style={summaryStyle}>
          {summary.split('\n').map((line, index) => (
            <p key={index} style={summaryLineStyle}>
              {line}
            </p>
          ))}

          <button
            onClick={copySummary}
            style={{
              ...buttonStyle,
              marginTop: '18px'
            }}
          >
            Copy Summary
          </button>

          <button
            onClick={generateSummary}
            disabled={generating}
            style={{
              ...secondaryButtonStyle,
              marginTop: '18px',
              marginLeft: '12px'
            }}
          >
            {generating ? 'Regenerating...' : 'Regenerate'}
          </button>
        </div>
      )}

      {error && <p style={errorStyle}>{error}</p>}

      <p style={footerStyle}>Generated by VedaByte Intelligence</p>
    </PremiumCard>
  )
}

const labelStyle = {
  color: '#D4AF37',
  letterSpacing: '0.28em',
  fontSize: '11px',
  fontWeight: '900',
  textTransform: 'uppercase',
  marginBottom: '10px'
}

const titleStyle = {
  color: '#FFFFFF',
  fontSize: '28px',
  lineHeight: '1.15',
  margin: 0
}

const textStyle = {
  color: '#C7C7C7',
  lineHeight: '1.8',
  maxWidth: '680px',
  marginBottom: '22px'
}

const topRowStyle = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: '18px'
}

const iconStyle = {
  width: '58px',
  height: '58px',
  borderRadius: '18px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  fontSize: '28px',
  background: 'linear-gradient(145deg, #151515, #060606)',
  border: '1px solid rgba(212,175,55,0.25)'
}

const dividerStyle = {
  height: '1px',
  background:
    'linear-gradient(90deg, transparent, rgba(212,175,55,0.65), transparent)',
  margin: '24px 0'
}

const summaryStyle = {
  color: '#DADADA',
  lineHeight: '1.8'
}

const summaryLineStyle = {
  marginBottom: '10px'
}

const buttonStyle = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: 'linear-gradient(135deg, #D4AF37, #FFE08A)',
  color: '#000',
  border: 'none',
  padding: '13px 24px',
  borderRadius: '999px',
  fontWeight: '900',
  textDecoration: 'none',
  cursor: 'pointer'
}

const secondaryButtonStyle = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: '#151515',
  color: '#D4AF37',
  border: '1px solid rgba(212,175,55,0.35)',
  padding: '13px 24px',
  borderRadius: '999px',
  fontWeight: '900',
  cursor: 'pointer'
}

const footerStyle = {
  color: '#777',
  marginTop: '16px',
  fontSize: '12px'
}

const errorStyle = {
  color: '#ef4444',
  marginTop: '14px'
}

const loadingBoxStyle = {
  background: '#0B0B0B',
  border: '1px solid rgba(212,175,55,0.22)',
  borderRadius: '18px',
  padding: '18px',
  marginBottom: '20px'
}

const loadingTextStyle = {
  color: '#D4AF37',
  fontWeight: '800',
  marginBottom: '10px'
}

const loadingBarStyle = {
  height: '8px',
  background: '#050505',
  borderRadius: '999px',
  overflow: 'hidden',
  marginBottom: '10px'
}

const loadingFillStyle = {
  width: '70%',
  height: '100%',
  background: 'linear-gradient(90deg, #D4AF37, #FFE08A)',
  borderRadius: '999px'
}

const loadingSmallStyle = {
  color: '#9CA3AF',
  fontSize: '13px',
  margin: 0
}